# Uncomment the next line to define a global platform for your project
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '12.0'

target 'Trocr' do

    config = use_native_modules!
     use_react_native!(
       :path => config[:reactNativePath],
       # to enable hermes on iOS, change `false` to `true` and then install pods
       :hermes_enabled => false
     )
     target 'TrocrTests' do
       inherit! :complete
       # Pods for testing
     end

    use_flipper!({'Flipper' => '0.141.0'})

        post_install do |installer|
          react_native_post_install(installer)
            installer.pods_project.targets.each do |target|
                target.build_configurations.each do |config|
                  config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
                end
            end
        end
end
